### ISSUE TITLE
Topaz.sh Documentation Update Needed, go-aserto vs aserto-go

### ISSUE THREAD

**Issue by expertonium** [aserto-dev/go-aserto#13]
On this page [topaz.sh: Authorizer Client](https://www.topaz.sh/docs/software-development-kits/go/authorizer), the imports reference `aserto-go`, and should be updated to `go-aserto`.

**Comment by gertd** [comment]
Thank you for reporting this, there is a PR up to address this https://github.com/aserto-dev/go-aserto/issues/13
